notifications:
  slack:
    rooms:
      - supla:dauFpwhgEGeyy9ERzqOYeJyY#github

matrix:
  include:
    - language: python
      python: 2.7
      install:
        - pip install cpplint

      script:
        - ./tools/lint.sh

    - env: OS=debian DIST=buster
    - language: cpp
      sudo: false
      os: linux
      compiler: gcc
      install:
        - sudo apt-get -y install valgrind
      script:
        - ./tools/test.sh

