sudo: false
language:  cpp
os: linux

notifications:
  slack:
    rooms:
      - supla:dauFpwhgEGeyy9ERzqOYeJyY#github

compiler:
  - gcc

script: 
  - cd supla-server/Test
  - make clean && make all
  - ./supla-server
  - cd ../Release
  - make clean && make all 
  - cd ../../supla-scheduler/Test
  - make clean && make all
  - ./supla-scheduler
  - cd ../Release
  - make clean && make all
