notifications:
  slack:
    rooms:
      - supla:dauFpwhgEGeyy9ERzqOYeJyY#github

matrix:
  include:
    - language: python
      python: 2.7
      install:
        - pip install cpplint

      script:
        - cpplint ./supla-server/src/*
        - cpplint ./supla-server/src/test/*
        - cpplint ./supla-scheduler/src/*
        - cpplint ./supla-scheduler/src/test/*
        - cpplint ./supla-dev/src/*
        - cpplint ./supla-client/src/*
        - cpplint ./supla-console-client/src/*
        - cpplint ./supla-console-client/src/supla-client-lib/*

    - language: cpp
      sudo: false
      os: linux
      compiler: gcc
      script:
        - cd supla-server/Test
        - make clean && make all
        - ./supla-server
        - cd ../Release
        - make clean && make all 
        - cd ../../supla-scheduler/Test
        - make clean && make all
        - ./supla-scheduler
        - cd ../Release
        - make clean && make all
        - cd ../../supla-dev/Release
        - make clean && make
        - cd ../../supla-console-client/Debug
        - make clean && make

