mqtt:
  host: 'mqttserverhost'
  port: 1883 
  commands_file_path: '../config/command.yaml'
  states_file_path: '../config/state.yaml' 
  client_name: 'supla_mqtt_client'
  protocol_version: 5
  publish_supla_events: true
supla:
  port: 2016
  host: 'localhost'
  access_id: 2
  password: 'password'
  protocol_version: 10
