name: supla-pushover-develop

on: 
  push:
    branches: 
    - supla-pushover-develop
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'supla-console-client/src'
        extensions: 'h,cpp,c'
        clangFormatVersion: 9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
