name: supla-pushover-develop

on: 
  push:
    branches: 
    - supla-pushover-develop
	
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
    - name: Clang Code Formatter
      uses: antoinealb/clang-format-action@clang9
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
