name: supla-pushover-develop

on: 
  push:
    branches: 
    - supla-pushover-develop
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'supla-console-client/src'
        extensions: 'h,cpp,c'
        clangFormatVersion: 9
        exclude: 'supla-console-client/src/supla-client-lib'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - run: cd supla-console-client/Release && make all
      
   
